# Application
spring.application.name=login-service

# Datasource PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/satmonitor_db
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Server
server.port=8087

# Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/microservices-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

#
jwt.auth.converter.resource-id=login-service
jwt.auth.converter.principle-attribute=preferred_username


# Keycloak admin pour créer des utilisateurs
keycloak.admin.client-id=admin-cli
keycloak.admin.username=admin
keycloak.admin.password=admin

# Keycloak client pour login-service
keycloak.client.id=login-service
keycloak.client-secret=7Zv9k8f877p6apSOyaiJBQNpMfNwrgoS
keycloak.realm=microservices-realm
keycloak.server-url=http://localhost:8081

# Application-cookie
app.cookie.secure=false
app.cookie.same-site=None