server.port=7079
spring.application.name=satmonitor-gateway

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true


# Gateway: discovery locator
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Default filters
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
spring.cloud.gateway.default-filters[1]=SetResponseHeader=Access-Control-Allow-Credentials, true
spring.cloud.gateway.default-filters[2]=SetResponseHeader=Access-Control-Expose-Headers, Set-Cookie


# Actuator
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always

# Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/microservices-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

#
jwt.auth.converter.resource-id=login-service
jwt.auth.converter.principle-attribute=preferred_username


